### PR TITLE
Update code_style of wrap_nncf_model

### PR DESCRIPTION
**Pull request by kshpv**

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
2 @aleksei-kashapov :   
1. Please, return back the error message
    ```python
            logger.info('Received non-NNCF checkpoint to start training '
                          '-- initialization of NNCF fields will be done')
    ```
2.  Please, move the following code above the functions `_get_fake_data_for_forward` and `dummy_forward` 
    ```python
      if "nncf_compress_postprocessing" in cfg:
          nncf_compress_postprocessing = cfg.get('nncf_compress_postprocessing')
          logger.debug('set should_compress_postprocessing='f'{nncf_compress_postprocessing}')
      else:
          nncf_compress_postprocessing = False
    ```
    (we investigated that it is not mandatory and the code will work, nevertheless it's better style)
3. Make `nncf_compress_postprocessing = True` by default
    Otherwise all my old config files will be broken
4. Please, return back the comment
    ```python
      if 'nncf_should_compress_postprocessing' in cfg:
          # NB: This parameter is used to choose if we should try to make NNCF compression
          #     for a whole model graph including postprocessing (`dummy_forward_with_export_part`),
          #     or make NNCF compression of the part of the model without postprocessing
          #     (`dummy_forward_without_export_part`).
          #     Our primary goal is to make NNCF compression of such big part of the model as
          #     possible, so `dummy_forward_with_export_part` is our primary choice, whereas
          #     `dummy_forward_without_export_part` is our fallback decision.
          #     When we manage to enable NNCF compression for sufficiently many models,
          #     we should keep one choice only.
    ```
    --- please, note that I made this comment intentionally (Pavel asked me to insert this comment)
5. Rebase on the top of my branch
    Sorry, it is a must

**Comment by LeonidBeynenson** [comment]
One more comment -- on the string
```
'set should_compress_postprocessing='f'{nncf_compress_postprocessing}'
```
-- please, don't do it! just make one f-string

**Comment by kshpv** [comment]
> One more comment -- on the string
> 
> ```
> 'set should_compress_postprocessing='f'{nncf_compress_postprocessing}'
> ```
> 
> -- please, don't do it! just make one f-string

it is your line, I didn't add it. LOL

**Comment by kshpv** [comment]
> 2 @aleksei-kashapov :
> 
> 1. Please, return back the error message
>    ```python
>            logger.info('Received non-NNCF checkpoint to start training '
>                          '-- initialization of NNCF fields will be done')
>    ```
> 2. Please, move the following code above the functions `_get_fake_data_for_forward` and `dummy_forward`
>    ```python
>      if "nncf_compress_postprocessing" in cfg:
>          nncf_compress_postprocessing = cfg.get('nncf_compress_postprocessing')
>          logger.debug('set should_compress_postprocessing='f'{nncf_compress_postprocessing}')
>      else:
>          nncf_compress_postprocessing = False
>    ```
>    
>    
>    (we investigated that it is not mandatory and the code will work, nevertheless it's better style)
> 3. Make `nncf_compress_postprocessing = True` by default
>    Otherwise all my old config files will be broken
> 4. Please, return back the comment
>    ```python
>      if 'nncf_should_compress_postprocessing' in cfg:
>          # NB: This parameter is used to choose if we should try to make NNCF compression
>          #     for a whole model graph including postprocessing (`dummy_forward_with_export_part`),
>          #     or make NNCF compression of the part of the model without postprocessing
>          #     (`dummy_forward_without_export_part`).
>          #     Our primary goal is to make NNCF compression of such big part of the model as
>          #     possible, so `dummy_forward_with_export_part` is our primary choice, whereas
>          #     `dummy_forward_without_export_part` is our fallback decision.
>          #     When we manage to enable NNCF compression for sufficiently many models,
>          #     we should keep one choice only.
>    ```
>    
>    
>    --- please, note that I made this comment intentionally (Pavel asked me to insert this comment)
> 5. Rebase on the top of my branch
>    Sorry, it is a must

1. I changed this message to easier understandable
2. I don't think that it makes sense. But it looks better if it is on the top of `_get_fake_data_for_forward` . So I updated
3. Make sense
4. Okay
5. No problem

**Pull request merged**
